#!/usr/bin/bash
echo "#pragma once" > include/stations.hpp
echo "
/**
THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE.

You can include this file to use Stations. However, if you would like to make changes, please only change to the original source files.
*/
" >> include/stations.hpp
grep -v "^#pragma " include/stations/worker_queue.hpp >> include/stations.hpp
find include/stations -name "*.hpp" -not -empty ! -name "worker_queue.hpp" -exec grep -v "^#pragma" {} \; >> include/stations.hpp
